spring:
  profiles:
    # active: local 
    active: prod
  application:
    name: bookmarker

naver:
  apiUrl: https://openapi.naver.com/v1/search/book.json

logging:
  level:
    org.springframework: INFO # Spring 관련 로그 레벨 설정
