server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

naver:
  clientId: ${CLIENT_ID}
  clientPw: ${CLIENT_PW}

jwt:
  secretKey: ${SECRET_KEY}