name: Keep Alive

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: curl -fsS -m 10 --retry 3 https://bkmk-1.onrender.com/ping || true